@startuml
class User {
  - userId
  - username
  - password
  - firstname
  - lastname
  - age
  + updateUserDetails()
  + getUserDetails()
  + createUserDetails()
}

class Environments {
   - environmentId
   - environmentName
   + createEnvironment()
   + renameEnvironment()
   + deleteEnvironment()
   + updateEnvironment()
}

class Projects {
   - projectId
   - projectName
   - avatar
   + createProject()
   + renameProject()
   + deleteProject()
   + updateProject()
}

class Group {
   - groupId
   - groupType
   + createGroup()
   + addToGroup()
   + removeFromGroup()
   + deleteGroup()
}

class Services {
   + disableService()
   + enableService()
}

class LiveMessaging {
   - liveMessagingId
   - receiver
   + sendMessage()
   + deleteMessage()
   + editMessage()
}

class LiveVoiceCalls {
   - liveVoiceCallId
   - receiver
   + startVoiceCall()
   + endVoiceCall()
}

class LiveVideoCalls {
   - liveVideoCallId
   - receiver
   + startVideoCall()
   + endVideoCall()
}

class 2dWorkflowTracker {
   - trackerId
   + addNodeToTrack()
   + removeTrackingNode()
}


class Ai {
   - aiId
   - aiModelType
   + summarizeData()
   + explainData()
   + createQuestion()
   + askQuestion()
   + sendAnswer()
}

class Team {
   - teamId
   - teamName
   - avatar
   + createTeam()
   + renameTeam()
   + deleteTeam()
   + updateTeam()
}

class History {
    + addHistory()
    + searchHistory()
    + restoreHistory()
}

class Search {
    + search()
}

class Files {
   - fileId
   - fileName
   - fileMetaData
   - fileType
   + createFile()
   + renameFile()
   + deleteFile()
   + updateFile()
}

class Trash {
   - trashId
   + addTrash()
   + restoreTrash()
   + deleteTrash()
}

class ExternalApps {
   - externalAppId
   - externalAppType
   - externalName
   + createLinkExternalApp()
   + deleteLinkExternalApp()
}

User --|> Environments
Environments --|> Projects
Environments --|> Group
Projects --|> Team
Projects --|> Services
Projects --|> Trash
Projects --|> History
Files --|> Trash
Services ..> ExternalApps
Services ..> Ai
Services ..> LiveMessaging
Services ..> LiveVideoCalls
Services ..> LiveVoiceCalls
Services ..> 2dWorkflowTracker
Group --|> Projects
Group --|> Files
Files --|> History
Team --> User
Search --> History
Search --> Environments

@enduml
